import { runId as makeRunId, shortId, sleep } from "@/lib/utils";
import { makeAgents, guardianOf } from "./agents";
import {
  decideAction,
  generateWorld,
  claudeConfigured,
  counterProposal,
  ghostModelId,
  reviewProposal,
  synthesizePostMortem,
  type GeneratedWorld,
} from "./brain";
import { emit } from "./bus";
import {
  applyAction,
  cloneNodes,
  computeMetrics,
  isStabilized,
  outcomeFor,
  unsafeReason,
  worldHash,
} from "./engine";
import { groundScenario } from "./grounding";
import { integrationStatus } from "./integrations";
import { captureGhostError } from "./observability";
import { startGhostWorkflow } from "./orkes";
import * as runStore from "./runStore";
import type {
  AgentAction,
  GhostAgent,
  GhostRequest,
  GhostRunMeta,
  Grounding,
  NarrationTone,
  PostMortem,
  Scenario,
  TraceSpan,
  WorkflowStepId,
  WorldNode,
} from "./types";

// ============================================================================
// Ghost Protocol orchestrator — a real multi-agent loop. Nothing is scripted:
// Claude designs the world from the prompt + live advisories, and each agent
// chooses its own action every tick. Conflicts (and the negotiation that
// resolves them) emerge when an agent's choice threatens critical infra.
// ============================================================================

const MAX_TICKS = 5;
const WALL_CAP_MS = 120_000;
const D = { phase: 200, step: 140, betweenTicks: 360 };

export function runGhostScenario(req: GhostRequest): string {
  const id = makeRunId();
  const meta: GhostRunMeta = {
    runId: id,
    prompt: req.prompt,
    scenarioId: "",
    title: "Crisis scenario",
    createdAt: Date.now(),
    status: "running",
  };
  runStore.createRun(meta);
  void execute(id, meta, req);
  return id;
}

function scenarioFromWorld(gen: GeneratedWorld, prompt: string, grounding: Grounding): Scenario {
  return {
    id: shortId("scn"),
    title: gen.title,
    domain: gen.domain,
    prompt,
    summary: gen.summary,
    threatType: gen.threatType,
    timeLimitSec: gen.timeLimitSec,
    nodes: gen.nodes as WorldNode[],
    agentRoles: gen.agentRoles,
    grounding,
    source: "llm",
  };
}

function worldSummary(nodes: WorldNode[]): string {
  const off = nodes.filter((n) => n.status === "offline").map((n) => n.label);
  const comp = nodes.filter((n) => n.status === "compromised").map((n) => n.label);
  const crit = nodes.filter((n) => n.critical).map((n) => n.label);
  return `offline: ${off.join(", ") || "none"} · compromised: ${comp.join(", ") || "none"} · critical: ${crit.join(", ") || "none"}`;
}

async function execute(id: string, meta: GhostRunMeta, req: GhostRequest): Promise<void> {
  const startedAt = Date.now();
  const now = () => Date.now();
  const timeline: { tick: number; label: string; tone: NarrationTone }[] = [];

  const narrate = (tick: number, text: string, tone: NarrationTone) => {
    timeline.push({ tick, label: text, tone });
    emit({ type: "narration", runId: id, narration: { id: shortId("nar"), tick, text, tone }, ts: now() });
  };
  const step = (tick: number, s: WorkflowStepId, status: "running" | "done" | "skipped") =>
    emit({ type: "workflow_step", runId: id, tick, step: s, status, ts: now() });

  try {
    const integrations = integrationStatus();
    emit({ type: "run_started", runId: id, meta, integrations, ts: now() });

    if (!claudeConfigured()) {
      throw new Error("Ghost Protocol needs ANTHROPIC_API_KEY: the world and every agent decision are generated by Claude — there is no canned scenario.");
    }

    // 1) Real threat grounding (Browserbase → live CISA advisories).
    const grounding = await groundScenario(req.prompt);
    emit({ type: "grounding", runId: id, grounding, ts: now() });

    // Real Orkes workflow execution (best-effort, runs alongside).
    try {
      const wf = await startGhostWorkflow({ scenario: req.prompt.slice(0, 80), threat: grounding.advisories[0]?.title ?? "infrastructure crisis" });
      if (wf) emit({ type: "orkes_workflow", runId: id, workflowId: wf.workflowId, url: wf.url, ts: now() });
    } catch {
      /* native orchestration drives the loop */
    }

    // 2) Claude designs the world from the prompt + advisories.
    const gen = await generateWorld(req.prompt, grounding.advisories);
    if (!gen) {
      throw new Error("Claude could not design a world from this prompt. Try a more specific crisis description (what's failing, what's under attack, who's at risk, and the deadline).");
    }
    const scenario = scenarioFromWorld(gen.world, req.prompt, grounding);
    meta.scenarioId = scenario.id;
    meta.title = scenario.title;
    emit({ type: "scenario_parsed", runId: id, scenario, ts: now() });
    await sleep(D.phase);

    const world = cloneNodes(scenario.nodes);
    const compromisedIds = world.filter((n) => n.status === "compromised").map((n) => n.id);
    const initMetrics = computeMetrics(world, 0, scenario.timeLimitSec, compromisedIds);
    const initialAtRisk = initMetrics.populationAtRisk;
    emit({ type: "world_init", runId: id, nodes: cloneNodes(world), metrics: initMetrics, ts: now() });
    await sleep(D.phase);

    const agents = makeAgents(scenario.agentRoles);
    const guardian = guardianOf(agents);
    emit({ type: "agents_deployed", runId: id, agents, ts: now() });
    narrate(0, `Crisis scenario initialized for ${scenario.title}. Deploying ${agents.length} specialist agents.`, "alert");
    await sleep(D.phase);

    // 3) The agentic tick loop.
    const spans: TraceSpan[] = [];
    const conflictsRec: { tick: number; description: string; by: string }[] = [];
    let consensusLatencyTotal = 0;
    let conflictsResolved = 0;
    const recent: string[] = [];
    let tick = 0;

    const mkSpan = (agent: GhostAgent, t: number, latencyMs: number, chosen: string, considered: string[], rejected: { option: string; why: string }[], rationale: string, conflict: boolean): TraceSpan => ({
      id: shortId("span"),
      tick: t,
      agentId: agent.id,
      role: agent.role,
      model: ghostModelId(),
      source: "llm",
      latencyMs,
      worldHash: worldHash(world, t),
      context: worldSummary(world),
      chosen,
      considered,
      rejected,
      rationale,
      conflict,
    });

    while (tick < MAX_TICKS && Date.now() - startedAt < WALL_CAP_MS) {
      tick++;
      const secondsRemaining = Math.max(0, Math.round(scenario.timeLimitSec - (Date.now() - startedAt) / 1000));
      emit({ type: "tick_started", runId: id, tick, secondsRemaining, ts: now() });

      step(tick, "snapshot", "running");
      await sleep(D.step);
      step(tick, "snapshot", "done");

      // --- fan out: every agent reasons in parallel (real Claude) ---------
      step(tick, "fan_out", "running");
      for (const a of agents) emit({ type: "agent_phase", runId: id, agentId: a.id, phase: "observing", ts: now() });
      const results = await Promise.all(agents.map((a) => decideAction(a, world, scenario.threatType, recent)));
      step(tick, "fan_out", "done");

      // --- collect proposals + real trace spans ---------------------------
      step(tick, "collect", "running");
      const proposed: { agent: GhostAgent; action: AgentAction; span: TraceSpan }[] = [];
      for (let i = 0; i < agents.length; i++) {
        const a = agents[i];
        const r = results[i];
        if (!r) {
          emit({ type: "agent_phase", runId: id, agentId: a.id, phase: "reasoning", thought: "No decision returned (model unavailable) — holding.", ts: now() });
          continue;
        }
        const d = r.decision;
        emit({ type: "agent_phase", runId: id, agentId: a.id, phase: "reasoning", thought: d.rationale, ts: now() });
        const action: AgentAction = {
          id: shortId("act"),
          agentId: a.id,
          tick,
          kind: d.action.kind,
          target: d.action.target,
          source: d.action.source,
          magnitudeMW: d.action.magnitude,
          summary: d.action.summary,
        };
        const span = mkSpan(a, tick, r.latencyMs, action.summary, d.considered, d.rejected, d.rationale, false);
        emit({ type: "agent_action", runId: id, action, ts: now() });
        emit({ type: "trace_span", runId: id, span, ts: now() });
        emit({ type: "agent_phase", runId: id, agentId: a.id, phase: "proposing", ts: now() });
        spans.push(span);
        proposed.push({ agent: a, action, span });
        recent.push(`${a.name}: ${action.summary}`);
        await sleep(D.step);
      }
      step(tick, "collect", "done");

      // --- detect conflicts: an agent's choice endangering critical infra --
      step(tick, "detect_conflict", "running");
      const unsafe = proposed
        .map((p) => ({ p, u: unsafeReason(p.action, world) }))
        .filter((x) => x.u && guardian && x.p.agent.id !== guardian.id);
      await sleep(D.step);
      step(tick, "detect_conflict", "done");

      // --- negotiate: the guardian reviews the first unsafe proposal;
      //     any other unsafe proposals are held by safety default so critical
      //     infrastructure is never harmed ----------------------------------
      const conflict = unsafe[0];
      for (let k = 1; k < unsafe.length; k++) {
        const ux = unsafe[k];
        ux.p.action = { id: shortId("act"), agentId: ux.p.agent.id, tick, kind: "hold", summary: `Withheld — ${ux.u!.node.label} protection enforced.` };
      }
      if (conflict && conflict.u && guardian) {
        const { p, u } = conflict;
        step(tick, "negotiate", "running");
        p.span.conflict = true;
        emit({ type: "neg_message", runId: id, message: { id: shortId("msg"), tick, from: p.agent.id, to: "all", intent: "propose", protocol: "agent.action.v1", refAction: p.action.summary, body: p.action.summary }, ts: now() });
        emit({ type: "conflict", runId: id, tick, description: `${p.agent.name} proposed ${u.reason}; ${u.node.label} is critical infrastructure.`, vetoedAction: p.action.summary, by: guardian.id, ts: now() });
        conflictsRec.push({ tick, description: `${p.agent.name}: ${u.reason} on ${u.node.label}`, by: guardian.id });
        emit({ type: "agent_phase", runId: id, agentId: guardian.id, phase: "negotiating", ts: now() });

        const t0 = Date.now();
        const rev = await reviewProposal(guardian, p.agent.name, p.action.summary, u.node, world, grounding.advisories);
        const reviewMs = Date.now() - t0;

        if (rev && rev.review.veto) {
          emit({ type: "neg_message", runId: id, message: { id: shortId("msg"), tick, from: guardian.id, to: p.agent.id, intent: "veto", protocol: "safety.protect.v1", refAction: p.action.summary, body: rev.review.message, cite: rev.review.cite }, ts: now() });
          spans.push(mkSpan(guardian, tick, reviewMs, `Veto: ${u.reason}`, ["veto", "approve"], [], rev.review.rationale, true));

          const c0 = Date.now();
          const counter = await counterProposal(p.agent, rev.review.message, world);
          const counterMs = Date.now() - c0;

          if (counter && !unsafeReason({ kind: counter.counter.action.kind, target: counter.counter.action.target, source: counter.counter.action.source }, world)) {
            p.action = { id: shortId("act"), agentId: p.agent.id, tick, kind: counter.counter.action.kind, target: counter.counter.action.target, source: counter.counter.action.source, magnitudeMW: counter.counter.action.magnitude, summary: counter.counter.action.summary };
            emit({ type: "neg_message", runId: id, message: { id: shortId("msg"), tick, from: p.agent.id, to: guardian.id, intent: "counter", protocol: "agent.action.v1", body: counter.counter.message }, ts: now() });
            emit({ type: "agent_action", runId: id, action: p.action, ts: now() });
            spans.push(mkSpan(p.agent, tick, counterMs, p.action.summary, [], [], counter.counter.rationale, true));
            emit({ type: "neg_message", runId: id, message: { id: shortId("msg"), tick, from: p.agent.id, to: "all", intent: "consensus", protocol: "consensus.v1", body: `Revised plan accepted; ${u.node.label} protected.` }, ts: now() });
            emit({ type: "consensus", runId: id, tick, summary: `${p.agent.name} found a safe alternative; ${u.node.label} protected.`, latencyMs: reviewMs + counterMs, ts: now() });
            consensusLatencyTotal += reviewMs + counterMs;
            conflictsResolved++;
            narrate(tick, `Conflict resolved: ${guardian.name} vetoed ${u.reason}; ${p.agent.name} rerouted safely. ${u.node.label} protected.`, "success");
          } else {
            p.action = { id: shortId("act"), agentId: p.agent.id, tick, kind: "hold", summary: `Stood down — no safe alternative; ${u.node.label} protected by ${guardian.name}.` };
            emit({ type: "agent_action", runId: id, action: p.action, ts: now() });
            narrate(tick, `${guardian.name} vetoed ${u.reason}; ${p.agent.name} stood down to protect ${u.node.label}.`, "conflict");
          }
        } else if (rev) {
          // Guardian explicitly cleared the action — it proceeds as proposed.
          emit({ type: "neg_message", runId: id, message: { id: shortId("msg"), tick, from: guardian.id, to: p.agent.id, intent: "ack", protocol: "safety.protect.v1", refAction: p.action.summary, body: rev.review.message }, ts: now() });
          spans.push(mkSpan(guardian, tick, reviewMs, `Cleared: ${p.action.summary}`, ["veto", "approve"], [], rev.review.rationale, true));
          narrate(tick, `${guardian.name} reviewed and cleared ${p.agent.name}'s action affecting ${u.node.label}.`, "info");
        } else {
          // Review unavailable → safety-default veto (block).
          emit({ type: "neg_message", runId: id, message: { id: shortId("msg"), tick, from: guardian.id, to: p.agent.id, intent: "veto", protocol: "safety.protect.v1", refAction: p.action.summary, body: `Safety default: action withheld to protect ${u.node.label}.` }, ts: now() });
          p.action = { id: shortId("act"), agentId: p.agent.id, tick, kind: "hold", summary: `Action withheld — ${u.node.label} protection enforced.` };
          emit({ type: "agent_action", runId: id, action: p.action, ts: now() });
          narrate(tick, `${u.node.label} protection enforced; ${p.agent.name}'s unsafe action withheld.`, "conflict");
        }
        step(tick, "negotiate", "done");
      } else {
        step(tick, "negotiate", "skipped");
      }

      // --- resolve + apply to the world -----------------------------------
      step(tick, "resolve", "running");
      await sleep(D.step);
      step(tick, "resolve", "done");

      step(tick, "apply", "running");
      for (const p of proposed) {
        const { changed, effect } = applyAction(world, { kind: p.action.kind, target: p.action.target, source: p.action.source, magnitude: p.action.magnitudeMW, summary: p.action.summary });
        emit({ type: "agent_phase", runId: id, agentId: p.agent.id, phase: "acting", ts: now() });
        if (changed) narrate(tick, `${p.agent.name}: ${effect}.`, "success");
      }
      const metrics = computeMetrics(world, tick, secondsRemaining, compromisedIds);
      emit({ type: "world_update", runId: id, nodes: cloneNodes(world), metrics, ts: now() });
      step(tick, "apply", "done");

      step(tick, "narrate", "running");
      await sleep(D.step);
      step(tick, "narrate", "done");
      step(tick, "advance", "running");
      step(tick, "advance", "done");

      while (recent.length > 6) recent.shift();
      if (isStabilized(world)) break;
      await sleep(D.betweenTicks);
    }

    // 4) Outcome + post-mortem from the REAL trace.
    const secondsLeft = Math.max(0, Math.round(scenario.timeLimitSec - (Date.now() - startedAt) / 1000));
    const finalMetrics = computeMetrics(world, tick, secondsLeft, compromisedIds);
    const outcome = outcomeFor(world, initialAtRisk);
    for (const a of agents) emit({ type: "agent_phase", runId: id, agentId: a.id, phase: "resolved", ts: now() });
    emit({ type: "resolved", runId: id, outcome, metrics: finalMetrics, ts: now() });
    await sleep(D.phase);

    const postMortem = await buildPostMortem({ scenario, outcome, spans, conflictsRec, finalMetrics, agents, consensusLatencyTotal, conflictsResolved, timeline });
    meta.outcome = outcome;
    emit({ type: "postmortem", runId: id, postMortem, ts: now() });
    await sleep(D.phase);

    emit({ type: "run_complete", runId: id, durationMs: Date.now() - startedAt, ts: now() });
  } catch (err) {
    captureGhostError(err, { runId: id, prompt: req.prompt });
    const message = err instanceof Error ? err.message : "Ghost Protocol run failed";
    emit({ type: "error", runId: id, message, ts: now() });
    emit({ type: "run_complete", runId: id, durationMs: Date.now() - startedAt, ts: now() });
  }
}

async function buildPostMortem(input: {
  scenario: Scenario;
  outcome: PostMortem["outcome"];
  spans: TraceSpan[];
  conflictsRec: { tick: number; description: string; by: string }[];
  finalMetrics: PostMortem["metrics"];
  agents: GhostAgent[];
  consensusLatencyTotal: number;
  conflictsResolved: number;
  timeline: { tick: number; label: string; tone: NarrationTone }[];
}): Promise<PostMortem> {
  const { scenario, outcome, spans, conflictsRec, finalMetrics, agents, consensusLatencyTotal, conflictsResolved, timeline } = input;
  const nameOf = (idv: string) => agents.find((a) => a.id === idv)?.name ?? idv;

  const agentTraces: Record<string, TraceSpan[]> = {};
  for (const a of agents) agentTraces[a.id] = spans.filter((s) => s.agentId === a.id);

  const synth = await synthesizePostMortem({
    title: scenario.title,
    outcome,
    trace: spans.map((s) => ({ tick: s.tick, agent: nameOf(s.agentId), action: s.chosen, rationale: s.rationale, conflict: s.conflict })),
    conflicts: conflictsRec.map((c) => ({ tick: c.tick, description: c.description, by: nameOf(c.by) })),
  });

  // Critical decision: prefer Claude's synthesis; else derive from the first real conflict span.
  const conflictSpan = spans.find((s) => s.conflict);
  const fallbackCritical = {
    tick: conflictSpan?.tick ?? spans[0]?.tick ?? 1,
    agentId: conflictSpan?.agentId ?? spans[0]?.agentId ?? agents[0]?.id ?? "",
    action: conflictSpan?.chosen ?? spans[0]?.chosen ?? "—",
    why: conflictSpan?.rationale ?? "Most consequential decision in the trace.",
    counterfactual: "Without this decision the crisis trajectory would have been materially worse.",
  };

  return {
    outcome,
    headline:
      synth?.data.headline ??
      (outcome === "stabilized"
        ? `${scenario.title}: agents stabilized the crisis with ${finalMetrics.populationAtRisk.toLocaleString()} still at risk.`
        : `${scenario.title}: ${finalMetrics.populationAtRisk.toLocaleString()} remained at risk at termination.`),
    summary: synth?.data.summary ?? `The agent team made ${spans.length} decisions across the run; ${conflictsResolved} conflict(s) were resolved through negotiation.`,
    criticalDecision: synth?.data.criticalDecision ?? fallbackCritical,
    timeline,
    conflictsResolved,
    consensusLatencyMs: consensusLatencyTotal,
    agentTraces,
    metrics: finalMetrics,
  };
}
